language: csharp
mono: none
sudo: required
dist: trusty
before_install:
  - curl -O https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.1
services:
  - memcached  
addons:
  hosts:
    - memcached      
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
  - linux
branches:
  only:
    - master
    - dotnetcore
    - dotnetcore2-preview2
script:
  - ./build.sh
  - ./test.sh
