language: csharp
mono: none
sudo: required
dist: trusty
before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.0.0-preview2-006497
services:
  - memcached  
addons:
  hosts:
    - memcached      
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
  - linux
branches:
  only:
    - master
    - dotnetcore
    - dotnetcore2-preview2
script:
  - ./build.sh
  - ./test.sh
